---
- name: "Check if directory {{ docker_compose_project_dir }} exists"
  ansible.builtin.stat:
    path: "{{ docker_compose_project_dir }}"
  register: stat_result

- name: "Print stat result - directory does not exist"
  ansible.builtin.debug:
    msg: "Directory does not exist. No cleanup taks will be run."
  when: 
    - stat_result.stat.isdir is undefined
    - stat_result.stat.exists == False

- name: "Print stat result - directory exists"
  ansible.builtin.debug:
    msg: "Directory exists. Continuing."
  when: 
    - stat_result.stat.isdir is defined
    - stat_result.stat.isdir

- name: "Start cleanup tasks"
  block:
    - name: "Run docker-compose down"
      community.docker.docker_compose:
        project_src: "{{ docker_compose_project_dir }}"
        files:
          - docker-compose.prod.yaml
        state: absent
      register: output_compose_down_prod

    - name: "Print docker-compose down output"
      ansible.builtin.debug:
        var: output_compose_down_prod

    - name: "Remove docker-compose project folder"
      ansible.builtin.file:
        path: "{{ docker_compose_project_dir }}"
        state: absent
  when: 
    - stat_result.stat.isdir is defined
    - stat_result.stat.isdir
