---
# tasks file for k4cg-wa
- name: "Install pre-requisites"
  ansible.builtin.include_tasks: "tasks/install_prerequisites.yml"
  when: install_prerequisites

- name: "Include cleanup tasks for specified environment"
  ansible.builtin.include_tasks: "tasks/cleanup_{{ env }}.yml"
  when: run_cleanup_tasks

- name: "Run deployment tasks for specified environment"
  ansible.builtin.include_tasks: "tasks/deploy_{{ env }}.yml"
  when: deploy_wa
